# Generated by Django 6.0.2 on 2026-02-12 05:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_role_field'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.TenantUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 08xxxxxxxx or 628xxxxxxxx', max_length=20, null=True),
        ),
    ]
