"""
Django settings for pondokindonesia project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'tenants',
    'users',
    'core',
    'crm',
    'hr',
    'portal',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'import_export',
]

UNFOLD = {
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "SITE_TITLE": "core.branding.get_site_title",
    "SITE_HEADER": "core.branding.get_site_header",
    "SITE_SYMBOL": "mosque",
    "COLORS": {
        "primary": {
            "50": "245 243 255",
            "100": "237 233 254",
            "200": "221 214 254",
            "300": "196 181 253",
            "400": "167 139 250",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "items": [
                    {
                        "title": "Dashboard Utama",
                        "icon": "home",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Manajemen Pengelola",
                "collapsible": True,
                "items": [
                    {
                        "title": "Data Pondok (Tenant)",
                        "icon": "business",
                        "link": "/admin/tenants/tenant/",
                        "permission": "core.permissions.is_superuser",
                    },
                    {
                        "title": "Pengguna SaaS",
                        "icon": "person",
                        "link": "/admin/users/user/",
                        "permission": "core.permissions.can_view_user",
                    },
                    {
                        "title": "Daftar Jabatan (Role)",
                        "icon": "badge",
                        "link": "/admin/users/role/",
                        "permission": "core.permissions.can_view_role",
                    },
                    {
                        "title": "Paket Berlangganan",
                        "icon": "loyalty",
                        "link": "/admin/core/pricingplan/",
                        "permission": "core.permissions.is_superuser",
                    },
                    {
                        "title": "Subscription Aktif",
                        "icon": "verified_user",
                        "link": "/admin/core/tenantsubscription/",
                        "permission": "core.permissions.is_superuser",
                    },
                ],
            },
            {
                "title": "CRM & Database",
                "collapsible": True,
                "items": [
                    {
                        "title": "Leads & Prospek",
                        "icon": "group_add",
                        "link": "/admin/core/lead/",
                        "permission": "core.permissions.can_view_lead",
                    },
                    {
                        "title": "Data Santri",
                        "icon": "school",
                        "link": "/admin/crm/santri/",
                        "permission": "core.permissions.can_view_santri",
                    },
                    {
                        "title": "Data Donatur",
                        "icon": "volunteer_activism",
                        "link": "/admin/crm/donatur/",
                        "permission": "core.permissions.can_view_donatur",
                    },
                    {
                        "title": "Program Pondok",
                        "icon": "list_alt",
                        "link": "/admin/crm/program/",
                        "permission": "core.permissions.can_view_program",
                    },
                ],
            },
            {
                "title": "Keuangan & Donasi",
                "collapsible": True,
                "items": [
                    {
                        "title": "Tagihan Santri",
                        "icon": "payments",
                        "link": "/admin/crm/tagihan/",
                        "permission": "core.permissions.can_view_tagihan",
                    },
                    {
                        "title": "Riwayat Donasi",
                        "icon": "receipt_long",
                        "link": "/admin/crm/transaksidonasi/",
                        "permission": "core.permissions.can_view_donasi",
                    },
                ],
            },
            {
                "title": "Integrasi WhatsApp & AI",
                "collapsible": True,
                "items": [
                    {
                        "title": "AI Knowledge Base",
                        "icon": "psychology",
                        "link": "/admin/core/aiknowledgebase/",
                        "permission": "core.permissions.can_view_aiknowledge",
                    },
                    {
                        "title": "Log Pesan WA",
                        "icon": "chat",
                        "link": "/admin/core/whatsappmessage/",
                        "permission": "core.permissions.is_superuser",
                    },
                    {
                        "title": "Auto Reply",
                        "icon": "reply",
                        "link": "/admin/core/whatsappautoreply/",
                        "permission": "core.permissions.is_superuser",
                    },
                    {
                        "title": "Formulir WA",
                        "icon": "description",
                        "link": "/admin/core/whatsappform/",
                        "permission": "core.permissions.is_superuser",
                    },
                ],
            },
            {
                "title": "Pengaturan Sistem",
                "collapsible": True,
                "items": [
                    {
                        "title": "API Integrasi",
                        "icon": "settings",
                        "link": "/admin/core/apisetting/",
                        "permission": "core.permissions.can_view_apisetting",
                    },
                ],
            },
            {
                "title": "Manajemen SDM",
                "collapsible": True,
                "items": [
                    {
                        "title": "Daftar Pengurus",
                        "icon": "badge",
                        "link": "/admin/hr/pengurus/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Daftar Jabatan",
                        "icon": "account_tree",
                        "link": "/admin/hr/jabatan/",
                        "permission": "core.permissions.can_view_jabatan",
                    },
                    {
                        "title": "Daftar Tugas",
                        "icon": "assignment",
                        "link": "/admin/hr/tugas/",
                        "permission": "core.permissions.can_view_tugas",
                    },
                    {
                        "title": "Absensi Harian",
                        "icon": "fact_check",
                        "link": "/admin/hr/absensi/",
                        "permission": "core.permissions.can_view_tugas",
                    },
                    {
                        "title": "Lokasi Kantor",
                        "icon": "location_on",
                        "link": "/admin/hr/lokasikantor/",
                        "permission": "core.permissions.can_view_lokasikantor",
                    },
                    {
                        "title": "Jadwal Kerja",
                        "icon": "schedule",
                        "link": "/admin/hr/jadwalkerja/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                ],
            },
            {
                "title": "Manajemen Kinerja (KPI)",
                "collapsible": True,
                "items": [
                    {
                        "title": "Periode Penilaian",
                        "icon": "date_range",
                        "link": "/admin/hr/periodepenilaian/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Kamus KPI",
                        "icon": "library_books",
                        "link": "/admin/hr/kamuskpi/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Target KPI Staff",
                        "icon": "track_changes",
                        "link": "/admin/hr/targetkpi/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Master Amalan",
                        "icon": "stars",
                        "link": "/admin/hr/jenisamalan/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Log Ibadah Harian",
                        "icon": "history_edu",
                        "link": "/admin/hr/logamalan/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                ],
            },
            {
                "title": "OKR (Objectives & Key Results)",
                "collapsible": True,
                "items": [
                    {
                        "title": "Objectives (Tujuan)",
                        "icon": "flag",
                        "link": "/admin/hr/objective/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                    {
                        "title": "Key Results (Hasil Kunci)",
                        "icon": "emoji_events",
                        "link": "/admin/hr/keyresult/",
                        "permission": "core.permissions.can_view_pengurus",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'pondokindonesia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pondokindonesia.wsgi.application'


# Database
# Use DB_URL or individual components from env
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}

# If DB_URL is not provided, try to assemble from individual env vars for MySQL
if not env('DATABASE_URL', default=None) and env('DB_NAME', default=None):
    DATABASES['default'] = {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='3306'),
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'users.backends.RolePermissionsBackend',
]

# Security Settings for Production
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'portal': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
