# Generated by Django 6.0.2 on 2026-02-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_lead_afu_count_lead_cs_lead_is_delivered_and_more'),
        ('crm', '0003_donatur_pic_fundraiser_santri_pic_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor WhatsApp')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Kode OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor WhatsApp')),
                ('user_type', models.CharField(choices=[('WALI', 'Wali Santri'), ('DONATUR', 'Donatur'), ('CALON_WALI', 'Calon Wali (Lead)')], max_length=20, verbose_name='Tipe User')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('donatur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donatur_sessions', to='crm.donatur')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sessions', to='core.lead')),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wali_sessions', to='crm.santri')),
            ],
            options={
                'verbose_name': 'Public User Session',
                'verbose_name_plural': 'Public User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
