# Generated by Django 6.0.2 on 2026-02-12 02:21

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')
    
    # Create Global Roles
    saas_admin = Role.objects.create(name='SaaS Admin', slug='saas_admin', is_system=True)
    tenant_admin = Role.objects.create(name='Tenant Admin', slug='tenant_admin', is_system=True)
    tenant_user = Role.objects.create(name='Tenant User', slug='tenant_user', is_system=True)
    
    roles_map = {
        'SAAS_ADMIN': saas_admin,
        'TENANT_ADMIN': tenant_admin,
        'TENANT_USER': tenant_user,
    }
    
    for user in User.objects.all():
        if user.role in roles_map:
            user.role_link = roles_map[user.role]
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_user_role_link'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles),
    ]
