# Generated by Django 6.0.2 on 2026-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_standard_lead_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donatur_id',
            field=models.IntegerField(blank=True, help_text='ID of related Donatur record', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_donatur',
            field=models.BooleanField(default=False, help_text='User is a Donatur'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lead',
            field=models.BooleanField(default=False, help_text='User is/was a Lead'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_wali',
            field=models.BooleanField(default=False, help_text='User is a Wali Santri'),
        ),
        migrations.AddField(
            model_name='user',
            name='lead_id',
            field=models.IntegerField(blank=True, help_text='ID of original Lead record (for conversion tracking)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='santri_id',
            field=models.IntegerField(blank=True, help_text='ID of related Santri record (if Wali)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff/Admin'), ('WALI', 'Wali Santri'), ('DONATUR', 'Donatur'), ('LEAD', 'Calon Wali/Donatur')], default='STAFF', help_text='User type for portal access control', max_length=20),
        ),
    ]
