# Generated by Django 6.0.2 on 2026-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_donatur_id_user_is_donatur_user_is_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wa_api_key',
            field=models.CharField(blank=True, help_text='Personal StarSender API Key. If filled, actions by this user will use this key.', max_length=255, null=True),
        ),
    ]
