# Generated by Django 6.0.2 on 2026-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apisetting_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(help_text='Device Name / Number', max_length=255)),
                ('message', models.TextField()),
                ('sender', models.CharField(help_text='From Number (Sender)', max_length=50)),
                ('timestamp', models.CharField(blank=True, help_text='Original timestamp from payload', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
