# Generated by Django 6.0.2 on 2026-02-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_whatsappmessage_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Sender Name (PushName)', max_length=100, null=True),
        ),
    ]
