# Generated by Django 6.0.2 on 2026-02-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whatsappmessage_sender_name'),
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SANTRI', 'Calon Santri'), ('DONATUR', 'Calon Donatur')], default='SANTRI', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dynamic data based on form format')),
                ('status', models.CharField(choices=[('NEW', 'Baru'), ('FOLLOW_UP', 'Sedang Diproses'), ('CLOSED', 'Selesai/Diterima'), ('REJECTED', 'Ditolak/Batal')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lead / Pendaftar',
                'verbose_name_plural': 'Leads / Pendaftar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="Keyword trigger, e.g. 'REG' or 'DAFTAR'", max_length=50)),
                ('separator', models.CharField(default='#', help_text="Character to separate data, e.g. '#'", max_length=5)),
                ('field_map', models.CharField(help_text="Field names separated by separator, e.g. 'nama#alamat#sekolah'", max_length=255)),
                ('lead_type', models.CharField(choices=[('SANTRI', 'Calon Santri'), ('DONATUR', 'Calon Donatur')], default='SANTRI', max_length=20)),
                ('response_template', models.TextField(default='Terima kasih {name}, data Anda telat kami terima.', help_text='Response message. Use {name} for sender name.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'WhatsApp Form',
                'verbose_name_plural': 'WhatsApp Forms',
                'ordering': ['keyword'],
            },
        ),
    ]
