# Generated by Django 6.0.2 on 2026-02-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lead_whatsappform'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappform',
            name='use_ai_response',
            field=models.BooleanField(default=False, help_text='If checked, the response_template will be used as a prompt for AI to generate the actual reply.'),
        ),
    ]
