# Generated by Django 6.0.2 on 2026-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_lead_utf8'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="e.g. 'Rp 0', 'Rp 249k', 'Custom'", max_length=100)),
                ('period', models.CharField(blank=True, help_text="e.g. '/bln'", max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(help_text="One feature per line. Use '✅ ' prefix if desired.")),
                ('cta_text', models.CharField(default='Pilih Paket', max_length=50)),
                ('cta_url', models.CharField(default='#', max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
    ]
