# Generated by Django 6.0.2 on 2026-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pricingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisetting',
            name='category',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp (StarSender)'), ('AI', 'Artificial Intelligence (Gemini/Groq)'), ('MEDIA', 'Media/Assets (Unsplash)'), ('PAYMENT', 'Payment Gateway (iPaymu)'), ('OTHER', 'Other Integrations')], default='OTHER', max_length=20),
        ),
    ]
