# Generated by Django 6.0.2 on 2026-02-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_apisetting_category'),
        ('tenants', '0003_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='can_use_ai',
            field=models.BooleanField(default=False, help_text='Akses fitur AI Assistant'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='can_use_ipaymu',
            field=models.BooleanField(default=False, help_text='Akses fitur Payment Gateway'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='can_use_whatsapp',
            field=models.BooleanField(default=False, help_text='Akses fitur Integrasi WhatsApp'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_donatur',
            field=models.PositiveIntegerField(default=100, help_text='Maksimal donatur (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_santri',
            field=models.PositiveIntegerField(default=100, help_text='Maksimal santri (0 = unlimited)'),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Kosongkan jika aktif selamanya', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricingplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
            },
        ),
    ]
