# Generated by Django 6.0.2 on 2026-02-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pricingplan_can_use_ai_pricingplan_can_use_ipaymu_and_more'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tenant_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Gallery Image',
                'verbose_name_plural': 'Tenant Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
