# Generated by Django 6.0.2 on 2026-02-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tenantgalleryimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='afu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_afu_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('WAITING_DATA', 'Menunggu Data'), ('NEW', 'Baru (Data Lengkap)'), ('FOLLOW_UP', 'Sedang Diproses'), ('INTERVIEW', 'Jadwal Interview'), ('ACCEPTED', 'Diterima'), ('CLOSED', 'Selesai (Lunas)'), ('REJECTED', 'Ditolak/Batal')], default='NEW', max_length=20),
        ),
    ]
