# Generated by Django 6.0.2 on 2026-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lead_afu_count_lead_cs_lead_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappform',
            name='auto_insert',
            field=models.BooleanField(default=False, help_text='Langsung insert ke tabel Santri/Donatur'),
        ),
        migrations.AddField(
            model_name='whatsappform',
            name='is_staff_only',
            field=models.BooleanField(default=False, help_text='Hanya bisa dipicu oleh staff terdaftar (format: username#...)'),
        ),
    ]
