# Generated by Django 6.0.2 on 2026-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_whatsappform_auto_insert_whatsappform_is_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_outbound',
            field=models.BooleanField(default=False, help_text='True if message is sent from system/staff to lead'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='recipient',
            field=models.CharField(blank=True, help_text='Destination Number (for outbound)', max_length=50, null=True),
        ),
    ]
