# Generated by Django 6.0.2 on 2026-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_whatsappmessage_is_outbound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgebase',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector representation of the content for semantic search', null=True),
        ),
    ]
