# Generated by Django 6.0.2 on 2026-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aiknowledgebase_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul panduan', max_length=200)),
                ('content', models.TextField(help_text='Isi panduan (Markdown suported)')),
                ('video_url', models.URLField(blank=True, help_text='Link video tutorial (Youtube/Loom)', null=True)),
                ('target_key', models.CharField(help_text="Identitas menu/modul (contoh: 'crm.santri', 'core.lead', 'dashboard')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial & Bantuan',
                'verbose_name_plural': 'Daftar Tutorial',
                'ordering': ['title'],
            },
        ),
    ]
