# Generated by Django 6.0.2 on 2026-02-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tutorial'),
        ('crm', '0014_santri_status_seleksi_alter_tagihanprogram_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='santri',
            field=models.ForeignKey(blank=True, help_text='Linked Santri record if converted or pre-existing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.santri'),
        ),
    ]
