# Generated by Django 6.0.2 on 2026-02-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lead_santri'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Bulan (1-12)')),
                ('year', models.IntegerField(default=2025, help_text='Tahun (e.g. 2025)')),
                ('target_donasi', models.DecimalField(decimal_places=2, default=0, help_text='Target perolehan donasi bulan ini', max_digits=15)),
                ('target_santri_baru', models.IntegerField(default=0, help_text='Target santri baru bulan ini')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Target Bulanan',
                'verbose_name_plural': 'Target Bulanan',
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
    ]
