# Generated by Django 6.0.2 on 2026-02-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_monthlytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, help_text='AI-generated Lead Score (0-100)'),
        ),
    ]
