# Generated by Django 6.0.2 on 2026-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Alamat lengkap pondok'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi profil pondok (bisa digenerate AI)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nomor WhatsApp official', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Deskripsi ringkas untuk hasil pencarian Google'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Judul halaman untuk Google', max_length=255),
        ),
    ]
