# Generated by Django 6.0.2 on 2026-02-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Jabatan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Jabatan')),
                ('atasan', models.ForeignKey(blank=True, help_text='Pilih atasan langsung untuk posisi ini. Kosongkan jika posisi tertinggi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bawahan', to='hr.jabatan', verbose_name='Atasan Langsung')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Daftar Jabatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIK / ID Pegawai')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat Tinggal')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus_foto/', verbose_name='Foto Profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anggota', to='hr.jabatan', verbose_name='Jabatan')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.OneToOneField(blank=True, help_text='Hubungkan dengan akun login untuk tracking kinerja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengurus_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun Login (Username)')),
            ],
            options={
                'verbose_name': 'Pengurus / Karyawan',
                'verbose_name_plural': 'Daftar Pengurus',
                'ordering': ['nama'],
            },
        ),
    ]
