# Generated by Django 6.0.2 on 2026-02-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lead_afu_count_lead_cs_lead_is_delivered_and_more'),
        ('hr', '0001_initial'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Tugas')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Detail')),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('PROSES', 'Sedang Dikerjakan'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan'), ('PENDING_APPROVAL', 'Menunggu Persetujuan')], default='BARU', max_length=20, verbose_name='Status')),
                ('prioritas', models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi')], default='SEDANG', max_length=20, verbose_name='Prioritas')),
                ('jenis', models.CharField(choices=[('PENUGASAN', 'Penugasan Langsung'), ('PERMINTAAN', 'Permintaan Lintas Divisi')], default='PENUGASAN', max_length=20, verbose_name='Jenis Tugas')),
                ('tenggat_waktu', models.DateTimeField(blank=True, null=True, verbose_name='Tenggat Waktu')),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('file', models.FileField(blank=True, null=True, upload_to='tugas_files/', verbose_name='Lampiran')),
                ('waktu_diselesaikan', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diselesaikan')),
                ('catatan_penyelesaian', models.TextField(blank=True, help_text='Catatan dari staf saat menyelesaikan tugas.', verbose_name='Catatan Penyelesaian')),
                ('bobot', models.IntegerField(default=3, help_text='1=Ringan, 3=Standar, 5=Strategis/KPI Utama. Digunakan untuk hitung rata-rata kinerja.', verbose_name='Bobot Nilai (1-5)')),
                ('skor', models.IntegerField(blank=True, help_text='Nilai kinerja untuk tugas ini (diisi oleh pemberi tugas).', null=True, verbose_name='Skor Kinerja (0-100)')),
                ('review_manager', models.TextField(blank=True, help_text='Catatan evaluasi dari pemberi tugas.', verbose_name='Review Manager')),
                ('lead', models.ForeignKey(blank=True, help_text='Pilih jika tugas ini berkaitan khusus dengan satu Lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_terkait', to='core.lead', verbose_name='Terkait Lead (Opsional)')),
                ('pembuat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tugas', to='hr.pengurus', verbose_name='Ditugaskan Kepada')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Daftar Tugas',
                'ordering': ['-tenggat_waktu'],
            },
        ),
    ]
