# Generated by Django 6.0.2 on 2026-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='url_posting',
            field=models.URLField(blank=True, help_text='Link konten yang sudah diposting (untuk bukti selesai).', null=True, verbose_name='Link Posting / Bukti Tayang'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('PROSES', 'Sedang Dikerjakan'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan'), ('PENDING_APPROVAL', 'Menunggu Persetujuan'), ('REVISI', 'Perlu Revisi')], default='BARU', max_length=20, verbose_name='Status'),
        ),
    ]
