# Generated by Django 6.0.2 on 2026-02-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_tugas_url_posting_alter_tugas_status'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiKantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kantor')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('radius_meter', models.IntegerField(default=50, help_text='Jarak maksimal karyawan bisa absen dari titik kantor.', verbose_name='Radius Toleransi (Meter)')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lokasi Kantor Absensi',
                'verbose_name_plural': 'Lokasi Kantor',
            },
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True, verbose_name='Tanggal')),
                ('waktu_masuk', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Masuk')),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to='absensi_masuk/', verbose_name='Foto Masuk')),
                ('lokasi_masuk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Koordinat Masuk')),
                ('waktu_keluar', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pulang')),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to='absensi_keluar/', verbose_name='Foto Pulang')),
                ('lokasi_keluar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Koordinat Pulang')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPA', 'Tanpa Keterangan')], default='HADIR', max_length=20, verbose_name='Status Kehadiran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan / Keterangan')),
                ('pengurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_absensi', to='hr.pengurus', verbose_name='Pengurus')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Absensi Harian',
                'verbose_name_plural': 'Data Absensi',
                'ordering': ['-tanggal', '-waktu_masuk'],
                'unique_together': {('tenant', 'pengurus', 'tanggal')},
            },
        ),
    ]
