# Generated by Django 6.0.2 on 2026-02-15 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_lokasikantor_absensi'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisAmalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Amalan')),
                ('poin', models.IntegerField(default=1, help_text='Poin yang didapat jika dikerjakan.', verbose_name='Bobot Poin')),
                ('is_wajib', models.BooleanField(default=False, help_text='Jika wajib, tidak dikerjakan bisa mengurangi nilai.', verbose_name='Wajib?')),
                ('kategori', models.CharField(blank=True, help_text='Contoh: Harian, Mingguan', max_length=50, null=True, verbose_name='Kategori')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Jenis Amalan',
                'verbose_name_plural': 'Jenis Amalan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='KamusKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Indikator')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi & Cara Hitung')),
                ('satuan', models.CharField(choices=[('PERCENT', 'Persentase (%)'), ('NUMBER', 'Angka (Nominal/Jumlah)'), ('CURRENCY', 'Mata Uang (Rp)')], max_length=20, verbose_name='Satuan')),
                ('sumber_data', models.CharField(choices=[('MANUAL', 'Input Manual'), ('AUTO_ABSENSI', 'Otomatis: Absensi (Kehadiran)'), ('AUTO_TUGAS', 'Otomatis: Penyelesaian Tugas'), ('AUTO_IBADAH', 'Otomatis: Skor Ibadah (Amalan)'), ('AUTO_SALES_LEAD', 'Otomatis: CRM (Leads Conversion)'), ('AUTO_FINANCE_SPP', 'Otomatis: Keuangan (Collection Rate)'), ('AUTO_FUNDRAISING', 'Otomatis: Fundraising (Total Donasi)')], default='MANUAL', max_length=30, verbose_name='Sumber Data')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Kamus KPI',
                'verbose_name_plural': 'Kamus KPI',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Q1 2025, Semester 1 2025', max_length=100, verbose_name='Nama Periode')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Periode Penilaian',
                'verbose_name_plural': 'Periode Penilaian',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TargetKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target')),
                ('bobot', models.IntegerField(help_text='Persentase kontribusi nilai ini terhadap total.', verbose_name='Bobot (%)')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.kamuskpi')),
                ('pengurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_kpi', to='hr.pengurus')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.periodepenilaian')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Target KPI',
                'verbose_name_plural': 'Target KPI',
                'unique_together': {('pengurus', 'periode', 'indikator', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='RealisasiKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Realisasi')),
                ('nilai_akhir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Skor Akhir (0-100)')),
                ('bukti_lampiran', models.FileField(blank=True, null=True, upload_to='bukti_kpi/', verbose_name='Bukti Lampiran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Evaluasi')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('target_kpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realisasi', to='hr.targetkpi')),
            ],
            options={
                'verbose_name': 'Realisasi KPI',
                'verbose_name_plural': 'Realisasi KPI',
            },
        ),
        migrations.CreateModel(
            name='LogAmalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True, verbose_name='Tanggal')),
                ('is_done', models.BooleanField(default=False, verbose_name='Dikerjakan')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan')),
                ('amalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jenisamalan')),
                ('pengurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_amalan', to='hr.pengurus')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Log Amalan',
                'verbose_name_plural': 'Log Amalan',
                'ordering': ['-tanggal'],
                'unique_together': {('pengurus', 'tanggal', 'amalan', 'tenant')},
            },
        ),
    ]
