# Generated by Django 6.0.2 on 2026-02-15 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_jenisamalan_kamuskpi_periodepenilaian_targetkpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='logamalan',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal'),
        ),
    ]
