# Generated by Django 6.0.2 on 2026-02-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_keyresult_tugas_key_result_objective_and_more'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Senin-Jumat, Shift Pagi', max_length=100, verbose_name='Nama Jadwal')),
                ('senin', models.BooleanField(default=True, verbose_name='Senin')),
                ('selasa', models.BooleanField(default=True, verbose_name='Selasa')),
                ('rabu', models.BooleanField(default=True, verbose_name='Rabu')),
                ('kamis', models.BooleanField(default=True, verbose_name='Kamis')),
                ('jumat', models.BooleanField(default=True, verbose_name='Jumat')),
                ('sabtu', models.BooleanField(default=False, verbose_name='Sabtu')),
                ('minggu', models.BooleanField(default=False, verbose_name='Minggu')),
                ('jam_masuk', models.TimeField(default='08:00', verbose_name='Jam Masuk')),
                ('jam_pulang', models.TimeField(default='17:00', verbose_name='Jam Pulang')),
                ('toleransi_telat', models.IntegerField(default=15, help_text="Menit keterlambatan yang masih dianggap 'Hadir'", verbose_name='Toleransi Terlambat (Menit)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='pengurus',
            name='jadwal_kerja',
            field=models.ForeignKey(blank=True, help_text='Jadwal kerja yang berlaku untuk staff ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_list', to='hr.jadwalkerja', verbose_name='Jadwal Kerja'),
        ),
    ]
