# Generated by Django 6.0.2 on 2026-02-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_donatur', models.CharField(blank=True, help_text='Auto-generated if empty', max_length=50, null=True)),
                ('nama_donatur', models.CharField(max_length=150)),
                ('no_hp', models.CharField(help_text='Nomor WhatsApp', max_length=50)),
                ('kategori', models.CharField(choices=[('TETAP', 'Donatur Tetap'), ('INSIDENTIL', 'Donatur Insidentil')], default='INSIDENTIL', max_length=20)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tgl_bergabung', models.DateField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Data Donatur',
                'verbose_name_plural': 'Data Donatur',
                'ordering': ['nama_donatur'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=150)),
                ('jenis', models.CharField(choices=[('TAGIHAN', 'Tagihan / SPP'), ('DONASI', 'Program Donasi')], default='TAGIHAN', max_length=20)),
                ('nominal_standar', models.DecimalField(decimal_places=0, default=0, help_text='Nominal default (bisa diubah saat transaksi)', max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Master Program',
                'verbose_name_plural': 'Master Program',
                'ordering': ['nama_program'],
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(help_text='Nomor Induk Santri (Unik per Tenant)', max_length=50)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nama_panggilan', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nama_wali', models.CharField(max_length=150)),
                ('no_hp_wali', models.CharField(help_text='Nomor WhatsApp Wali', max_length=50)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('LULUS', 'Lulus / Alumni'), ('CUTI', 'Cuti'), ('KELUAR', 'Keluar / DO')], default='AKTIF', max_length=20)),
                ('tgl_masuk', models.DateField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Data Santri',
                'verbose_name_plural': 'Data Santri',
                'ordering': ['nama_lengkap'],
                'unique_together': {('nis', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('bulan', models.CharField(blank=True, help_text='Contoh: Januari 2024', max_length=20, null=True)),
                ('status', models.CharField(choices=[('BELUM', 'Belum Lunas'), ('LUNAS', 'Lunas')], default='BELUM', max_length=20)),
                ('tgl_buat', models.DateTimeField(auto_now_add=True)),
                ('tgl_bayar', models.DateTimeField(blank=True, null=True)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(limit_choices_to={'jenis': 'TAGIHAN'}, on_delete=django.db.models.deletion.CASCADE, to='crm.program')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='crm.santri')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tagihan / SPP',
                'verbose_name_plural': 'Tagihan / SPP',
                'ordering': ['-tgl_buat'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiDonasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tgl_donasi', models.DateTimeField(auto_now_add=True)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_donasi/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi', to='crm.donatur')),
                ('program', models.ForeignKey(limit_choices_to={'jenis': 'DONASI'}, on_delete=django.db.models.deletion.CASCADE, to='crm.program')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transaksi Donasi',
                'verbose_name_plural': 'Transaksi Donasi',
                'ordering': ['-tgl_donasi'],
            },
        ),
    ]
