# Generated by Django 6.0.2 on 2026-02-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.SlugField(max_length=100)),
                ('value', models.TextField(help_text='Clear text for now, can be encrypted later.')),
                ('category', models.CharField(choices=[('WHATSAPP', 'WhatsApp (StarSender)'), ('AI', 'Artificial Intelligence (Gemini/Groq)'), ('MEDIA', 'Media/Assets (Unsplash)'), ('OTHER', 'Other Integrations')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(blank=True, help_text='Set NULL for global settings.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'API Setting',
                'verbose_name_plural': 'API Settings',
                'unique_together': {('key_name', 'tenant')},
            },
        ),
    ]
