# Generated by Django 6.0.2 on 2026-02-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_whatsappmessage'),
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword to trigger response (Case Insensitive)', max_length=100)),
                ('response', models.TextField(help_text='Response message')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'WhatsApp Auto Reply',
                'verbose_name_plural': 'WhatsApp Auto Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
