# Generated by Django 6.0.2 on 2026-02-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_whatsappautoreply'),
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text="Topic e.g., 'Biaya Pendaftaran', 'Jadwal'", max_length=200)),
                ('content', models.TextField(help_text='Detailed information about the topic')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI Knowledge Base',
                'verbose_name_plural': 'AI Knowledge Base',
                'ordering': ['topic'],
            },
        ),
    ]
