# Generated by Django 6.0.2 on 2026-02-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aiknowledgebase'),
        ('tenants', '0002_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
