# Generated by Django 6.0.2 on 2026-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsappform_use_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI Analysis Result (Interest, Summary, Recommendation)'),
        ),
    ]
