# Generated by Django 6.0.2 on 2026-02-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lead_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_draft',
            field=models.TextField(blank=True, help_text='Last AI-generated message draft.', null=True),
        ),
    ]
