# Generated by Django 6.0.2 on 2026-02-12 04:51

import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(max_length=100, unique=True, validators=[tenants.validators.validate_subdomain]),
        ),
    ]
