# Generated by Django 6.0.2 on 2026-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihan',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID Transaksi iPaymu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Link Pembayaran iPaymu', null=True),
        ),
        migrations.AddField(
            model_name='transaksidonasi',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID Transaksi iPaymu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksidonasi',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Link Pembayaran iPaymu', null=True),
        ),
    ]
