# Generated by Django 6.0.2 on 2026-02-15 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_tagihan_external_id_tagihan_payment_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donatur',
            name='pic_fundraiser',
            field=models.ForeignKey(blank=True, help_text='Staff yang bertanggung jawab atas donatur ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donatur_handled', to=settings.AUTH_USER_MODEL, verbose_name='PIC Fundraiser'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pic_admin',
            field=models.ForeignKey(blank=True, help_text='Staff yang bertanggung jawab atas penagihan SPP santri ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri_handled', to=settings.AUTH_USER_MODEL, verbose_name='PIC Admin / Wali Asuh'),
        ),
    ]
