# Generated by Django 6.0.2 on 2026-02-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_donatur_pic_fundraiser_santri_pic_admin'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagihanSPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField(help_text='Tanggal 1 dari bulan yang ditagih (e.g., 2026-02-01 untuk Feb 2026)', verbose_name='Bulan Tagihan')),
                ('jumlah', models.DecimalField(decimal_places=0, help_text='Nominal tagihan SPP bulan ini', max_digits=12, verbose_name='Jumlah Tagihan')),
                ('jatuh_tempo', models.DateField(help_text='Batas waktu pembayaran', verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('BELUM_LUNAS', 'Belum Lunas'), ('LUNAS', 'Lunas'), ('TERLAMBAT', 'Terlambat')], default='BELUM_LUNAS', max_length=20, verbose_name='Status Pembayaran')),
                ('tanggal_bayar', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pembayaran')),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan untuk tagihan ini', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_spp', to='crm.santri', verbose_name='Santri')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tagihan SPP',
                'verbose_name_plural': 'Tagihan SPP',
                'ordering': ['-bulan', 'santri'],
                'unique_together': {('santri', 'bulan', 'tenant')},
            },
        ),
    ]
