# Generated by Django 6.0.2 on 2026-02-15 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_tagihanspp'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank'), ('QRIS', 'QRIS')], max_length=20, verbose_name='Jenis Metode')),
                ('bank_name', models.CharField(blank=True, help_text='Contoh: BCA, Mandiri, BRI', max_length=100, verbose_name='Nama Bank')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Nomor Rekening')),
                ('account_name', models.CharField(blank=True, max_length=150, verbose_name='Nama Pemilik Rekening')),
                ('qris_image', models.ImageField(blank=True, help_text='Upload gambar QRIS untuk pembayaran', null=True, upload_to='payment_methods/qris/', verbose_name='Gambar QRIS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('display_order', models.IntegerField(default=0, help_text='Urutan tampilan di halaman pembayaran (lebih kecil = lebih atas)', verbose_name='Urutan Tampilan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['display_order', 'method_type'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranSPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_bayar', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jumlah Dibayar')),
                ('bukti_transfer', models.ImageField(upload_to='bukti_pembayaran/', verbose_name='Bukti Transfer')),
                ('tanggal_transfer', models.DateField(help_text='Tanggal melakukan transfer', verbose_name='Tanggal Transfer')),
                ('catatan_pembayar', models.TextField(blank=True, help_text='Catatan tambahan dari pembayar', verbose_name='Catatan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20, verbose_name='Status Verifikasi')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan dari admin saat verifikasi', verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.paymentmethodsetting', verbose_name='Metode Pembayaran')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='crm.tagihanspp', verbose_name='Tagihan SPP')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Pembayaran SPP',
                'verbose_name_plural': 'Pembayaran SPP',
                'ordering': ['-created_at'],
            },
        ),
    ]
