# Generated by Django 6.0.2 on 2026-02-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_paymentmethodsetting_pembayaranspp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihanspp',
            name='tanggal_bayar',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pembayaran'),
        ),
    ]
