# Generated by Django 6.0.2 on 2026-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_tagihanspp_tanggal_bayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='tgl_bayar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
