# Generated by Django 6.0.2 on 2026-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_tagihan_tgl_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksidonasi',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20),
        ),
    ]
