# Generated by Django 6.0.2 on 2026-02-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_transaksidonasi_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagihan',
        ),
    ]
