# Generated by Django 6.0.2 on 2026-02-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_tagihan'),
        ('tenants', '0004_tenant_address_tenant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihanspp',
            name='program',
            field=models.ForeignKey(blank=True, limit_choices_to={'jenis': 'TAGIHAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagihan_spp', to='crm.program', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='TagihanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Nominal')),
                ('jatuh_tempo', models.DateField(verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('BELUM', 'Belum Lunas'), ('LUNAS', 'Lunas'), ('TERLAMBAT', 'Terlambat')], default='BELUM', max_length=20, verbose_name='Status')),
                ('tanggal_bayar', models.DateField(blank=True, null=True, verbose_name='Tanggal Bayar')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_program_set', to='crm.program', verbose_name='Program')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_program', to='crm.santri', verbose_name='Santri')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tagihan Program',
                'verbose_name_plural': 'Tagihan Program',
                'ordering': ['-jatuh_tempo'],
            },
        ),
    ]
