# Generated by Django 6.0.2 on 2026-02-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_tagihanspp_program_tagihanprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihanprogram',
            name='program',
            field=models.ForeignKey(limit_choices_to={'jenis': 'TAGIHAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_program_set', to='crm.program', verbose_name='Program'),
        ),
    ]
