# Generated by Django 6.0.2 on 2026-02-18 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_tagihanprogram_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihanprogram',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID Transaksi iPaymu (Session ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagihanprogram',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Link Pembayaran iPaymu', null=True),
        ),
        migrations.AddField(
            model_name='tagihanspp',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID Transaksi iPaymu (Session ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagihanspp',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Link Pembayaran iPaymu', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='jenis',
            field=models.CharField(choices=[('TAGIHAN', 'Tagihan / SPP'), ('DONASI', 'Program Donasi'), ('PENDAFTARAN', 'Biaya Pendaftaran')], default='TAGIHAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksidonasi',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.program'),
        ),
    ]
