# Generated by Django 6.0.2 on 2026-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_tagihanprogram_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(choices=[('CALON', 'Calon Santri'), ('AKTIF', 'Aktif'), ('LULUS', 'Lulus / Alumni'), ('CUTI', 'Cuti'), ('KELUAR', 'Keluar / DO')], default='AKTIF', max_length=20),
        ),
    ]
