# Generated by Django 6.0.2 on 2026-02-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_santri_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='status_seleksi',
            field=models.CharField(choices=[('BELUM_TES', 'Belum Tes'), ('WAWANCARA', 'Proses Wawancara'), ('LULUS', 'Lulus Seleksi'), ('GAGAL', 'Tidak Lulus')], default='BELUM_TES', help_text='Status tahapan seleksi masuk', max_length=20),
        ),
        migrations.AlterField(
            model_name='tagihanprogram',
            name='program',
            field=models.ForeignKey(limit_choices_to=models.Q(('jenis', 'TAGIHAN'), ('jenis', 'PENDAFTARAN'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_program_set', to='crm.program', verbose_name='Program'),
        ),
    ]
